/* tslint:disable */
/* eslint-disable */
/**
 * MininCode API
 * API для работы с организациями на платформе \"MininCode\"
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

